### ISSUE TITLE
Functionality not working 

### ISSUE THREAD

**Issue by Sylvainp-Ribbonfish** [ChuckJonas/vscode-apex-autocomplete#13]
Hi,

I have installed the plugin, I managed to make it work for few seconds but then works sometime and I have this:
![screen shot 2017-03-24 at 17 31 08](https://cloud.githubusercontent.com/assets/10757268/24306214/b8e3995a-10b7-11e7-8558-f1f821e1cee1.png)

So I don't know what is wrong and also sometimes comments won't generate properly on the Information panel with the same comment working on other functions...

Project still active?

Thanks
Sylvain

**Comment by ChuckJonas** [comment]
Project is still active (pretty much updated weekly).

Can you run `Show Apex Autocomplete Debug Output` and paste the results from when its not working?  Be careful not to include your password.

Also....

What OS are you running?

**Comment by Sylvainp-Ribbonfish** [comment]
Hi,

I'm on Mac os, and the following requested:
[INFO] Executor - # Time taken: 2.102s

[ERROR] CheckSyntax - Syntax error:: line: 24, pos: 4, msg: no viable alternative at input 'Opport}'

[ERROR] CheckSyntax - Syntax error:: line: 24, pos: 4, msg: no viable alternative at input 'Opport}'

(The debugger works that you made).

**Comment by Sylvainp-Ribbonfish** [comment]
![screen shot 2017-03-24 at 17 38 40](https://cloud.githubusercontent.com/assets/10757268/24306512/c4a9718c-10b8-11e7-9bd4-2b7f7b934a66.png)
When it works it show that however I have a class called: OpportunityTriggerHandler not showing.

**Comment by Sylvainp-Ribbonfish** [comment]
[ERROR] CheckSyntax - Syntax error:: line: 24, pos: 4, msg: no viable alternative at input 'Opportunity}' => I typed Opportunity

**Comment by ChuckJonas** [comment]
That's just the syntax checking that your pasting into the output.   The autocomplete only completes on the `.` notation.   It currently doesn't autocomplete class or object names as you are typing.  It should work with methods & properties.  If it doesn't work, then please send me the log after you try the dot notation.  It should say something like `CMD: action="listCompletions"`

**Comment by carlosabella** [comment]
Hi, 

I have some mates in my company facing same problems. And it is interesting this command you posted: Show Apex Autocomplete Debug Output   

I am using windows 7 and I put this command on VSCode Debug Console. But I got this Message "Please start a debug session to evaluate"

How can I use " Apex Autocomplete Debug Output "? 
![image](https://cloud.githubusercontent.com/assets/4191627/24345535/00be7234-12d1-11e7-824a-fded8ac985fc.png)

Thanks!

**Comment by Sylvainp-Ribbonfish** [comment]
Ok I got it is working as you said however I still have a small issue regarding the comment display in the 'i' bubble:
[ERROR] CheckSyntax - Syntax error:: line: 25, pos: 4, msg: no viable alternative at input 'DataFactory.}' => This is showing even when it is working.

The screenshots:
![screen shot 2017-03-27 at 09 34 56](https://cloud.githubusercontent.com/assets/10757268/24347842/9ec1894e-12d1-11e7-945a-3c532285b240.png)
![screen shot 2017-03-27 at 09 35 11](https://cloud.githubusercontent.com/assets/10757268/24347843/9f4f353c-12d1-11e7-90af-df195e2c7f2b.png)
![screen shot 2017-03-27 at 09 35 35](https://cloud.githubusercontent.com/assets/10757268/24347844/9f5ba48e-12d1-11e7-946f-596e419a34e9.png)
As you can see the comment section is the same however it is not retrieving them properly for the 2 firsts methods and no debug is showing.

Thanks
Sylvain

**Comment by ChuckJonas** [comment]
`[ERROR] CheckSyntax - Syntax error:: line: 25, pos: 4, msg: no viable alternative at input 'DataFactory.}` is from the "Syntax checking" functionality and has nothing to do with autocomplete (it's what causes the green squiggle to show up on the next line).  

I'm not sure why the comment wouldn't load, given that the completion is being provided properly and the comment is properly formatted.  

This extension just leverages the [tooling-force.com](https://github.com/neowit/tooling-force.com) library to provide completion.  @neowit might be able to help if you create an issue over there.

**Comment by Sylvainp-Ribbonfish** [comment]
Ok no problems thanks for your help 👍
