### ISSUE TITLE
Show Apex Autocomplete Debug Output

### ISSUE THREAD

**Issue by carlosabella** [ChuckJonas/vscode-apex-autocomplete#15]
Hi, 

I've seen in other issues you are using this command: Show Apex Autocomplete Debug Output

But I don't know where to run this command. I have some mates in my company that are having problems with this plugin; I woud like to help them to debug their problems. 

Thanks!

**Comment by ChuckJonas** [comment]
you can run it from the command pallet just like any other command in vscode.  On mac, the shortcut is `cmd-shift-p` to bring up the command pallet.

![package-generator_and_show_apex_autocomplete_debug_output_ _issue__15_ _chuckjonas_vscode-apex-autocomplete](https://cloud.githubusercontent.com/assets/5217568/24368242/eb4f8120-12dc-11e7-97c5-5d42c9680bb6.png)

**Comment by carlosabella** [comment]
Great!!
thanks a lot!
