### ISSUE TITLE
CPU usage extremely high and no results

### ISSUE THREAD

**Issue by toadgeek** [ChuckJonas/vscode-apex-autocomplete#17]
Hi there. First of all, thanks for taking some time to help me with this issue. 

This add-on is not working at all for me and I can't understand why. After installing and setting it up, the CPU usage is skyrocketing, and I get no results from the autocomplete. 

- macOS Sierra 10.12.4 (16E195)
- VS Code Version 1.11.2 (1.11.2)
- apexAutoComplete.userName , apexAutoComplete.password (password+security token) & apexAutoComplete.instanceUrl configured in my workspace settings.
- src folder in the root of my workspace.
- Java version 1.8.0_121.

Thanks!

**Comment by ChuckJonas** [comment]
@toadgeek how big is your project and what are the general specs on your machine?

**Comment by toadgeek** [comment]
We currently have 2307 classes and my machine specs are: 

Processor i7 2.7 Ghz, 16 GB DDR3 (Macbook Pro Retuba 15-inch)

Other plugins: Apex Syntax, ForceCode, Git, Sublime Text Keymap, Visualforce Syntax.

**Comment by ChuckJonas** [comment]
@toadgeek congradulations you win for the largest project I've come across.  My guess would be that vscode is timing out the autocomplete request before it has a chance to respond.   Could you try to load up a smaller project or reduce the number of classes and see if it starts to respond? 

Also running `Show Apex Autocomplete Debug console`  (using `cmp-shift-p`) will allow us to see a bit more information on what's going on behind the scenes (and maybe set `"apexAutoComplete.checkSyntax": "false"` to reduce noise).

@neowit have you ever run tooling-force with a project this large?

**Comment by toadgeek** [comment]
I've changed checkSyntax to false. This is what I got from the debug console: 

[INFO] Executor - # Time taken: 15.014s

[INFO] Executor - # Time taken: 24.928s

[INFO] Executor - # Time taken: 30.02s

Every time I type something, it starts to scan all the files again, and stops eventually without returning the results. I guess you're right, I guess it's hitting some timeout.

**Comment by ChuckJonas** [comment]
that's weird, you should see a log for the initiating command as well.  Also, after you disable `checkSyntax`, you would need to restart vscode for it to take effect.

**Comment by neowit** [comment]
> @neowit have you ever run tooling-force with a project this large?

Yes I have, but only for syntax check (as part of CI), and would not recommend using code completion on such a project. Initial parsing will take several minutes.

Syntax check on a single file should not be an issue, as it deals with just one file.
Code completion however has to take the whole project into consideration which means it has to:

1. parse every single apex class (which includes syntax check, as it is pretty much the same thing)
2. build and cache AST (which requires a lot of RAM)
3. finally run actual completion part (which includes AST traversing)

After the initial scan project's AST is cached in RAM (if you have enough of it), so subsequent calls to Code Completion should be quicker than the first one, but still with AST this large I would not expect acceptable response time.

If during initial parse and AST building another call (for completion) come in then you will not have two threads doing same thing and so on.

**Comment by toadgeek** [comment]
Alright, thanks for the update and the explanation, @neowit and @ChuckJonas. I'll try to use it in smaller projects.

**Comment by ChuckJonas** [comment]
@toadgeek I know it's less than ideal, but you could try to just pull down a subset of classes to work.  Thanks for submitting this issue, good to know the limits of this tool.
