### ISSUE TITLE
Getting "Invalid file resource" for valid files (but only on Windows machine)

### ISSUE THREAD

**Issue by IndigoTea** [ChuckJonas/vscode-apex-autocomplete#21]
![invalid_file_msg](https://cloud.githubusercontent.com/assets/11982840/26466689/443140f2-4155-11e7-8bea-138d4ebc85f4.PNG)

We're test-driving this for our org; my co-worker, who works on a Mac, has this working right out of the box. I'm using the same setup, but on Win10, and get the error as seen in the image above. Any suggestions?

**Comment by jamessimone** [comment]
I am using VS code 1.12.2 and this started happening to me a few releases ago - perhaps 4 weeks ago in total?  I just tried to uninstall the plugin and re-install it, and now I get an error message when trying to install it.

**Comment by ChuckJonas** [comment]
@IndigoTea @jamessimone does this happen after any particular action?  

The newest releases of vscode have made this extension more buggy (I'm a bit swamped right now but hope to be able to take a look soon).

**Comment by IndigoTea** [comment]
This was after initial install of the extension, and opening up a SF project; tried both F12 and right-click, same results - even if the origin was in the same page. I'm still very new to VS Code and SF (C#/Visual Studio background).

**Comment by jamessimone** [comment]
@ChuckJonas which version of VS code are you running at the moment?  I just went back to 1.10.2 and still no luck, unfortunately - although at least this time I was able to re-install the plugin!

**Comment by ChuckJonas** [comment]
@jamessimone I'm running the 1.12.1, but I actually think it might have to do with the new Document Symbol provider I added in 0.2.7.  I'll try to fire up a windows VM today and see if I can't replicate it.

**Comment by IndigoTea** [comment]
@ChuckJonas - whatever you can do, we'd greatly appreciate it. I can supply you the output in VS Code if it would be of any help. Your extension definitely fills a missing gap in VS Code usability for Salesforce development - thank you for your work on this!

**Comment by svelamoor** [comment]
@IndigoTea, @ChuckJonas  - There's a small fix in apexDefinitionProvider.js on line 27, replace with the following line. `Uri.parse` doesn't work. 

`let def = new vscode.Location(vscode.Uri.file(obj.filePath), new vscode.Range(obj.line - 1, obj.column, obj.line, obj.column));`

**Comment by IndigoTea** [comment]
@svelamoor - that worked a treat, thanks! @ChuckJonas - this extension has made working in Apex/VSCode far more usable - thanks to you as well!

**Comment by ChuckJonas** [comment]
patch released!

**Comment by svelamoor** [comment]
@ChuckJonas - Awesome! Thanks for the quick release!
