### ISSUE TITLE
tooling-force.jar does not get run when the path to it contains spaces

### ISSUE THREAD

**Issue by jperezq** [ChuckJonas/vscode-apex-autocomplete#24]
Whenever the plugin tries to pull intellisense information I get this on the console:
[Extension Host] stderr: Error: Unable to access jarfile C:\Users\Javier

Then of course it is unable to connect to the service and continues with:
connect ECONNREFUSED 127.0.0.1:65000

I gather this is because spaces in the path to the jar file are not getting escaped properly and I have a space on the folder name for my user's home.

This is on Windows 10 in case it matters.

**Comment by ChuckJonas** [comment]
Thanks for submitting this.  I'll try to take a look as soon as I can

**Comment by ChuckJonas** [comment]
@jperezq I just released an update with a potential fix from @Codeneos.  Could you test and let me know if it works now?

**Comment by jperezq** [comment]
Sorry, was not able to find time to look at this before. It's working great now. I still have performance issues with the huge project I'm working on, mirroring what was already discussed on #17 . I do understand that that's just how it is for now.

Thank you so much.
