### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by carlosabella** [ChuckJonas/vscode-apex-autocomplete#3]
Hi ChuckJonas,

This plugin doesen't works for me. This is my folder structure: 
![image](https://cloud.githubusercontent.com/assets/4191627/21561723/c7eec066-ce70-11e6-82fb-461449ba94f6.png)

And this is my workspace settings:
![image](https://cloud.githubusercontent.com/assets/4191627/21561760/5358b030-ce71-11e6-8f80-dffb572fabda.png)
I don't know what I am doing wrong. 

Thanks!

**Comment by ChuckJonas** [comment]
@carlosabella 

What OS are you using?

**Comment by carlosabella** [comment]
@ChuckJonas  Windows 7   x64 bit

**Comment by ChuckJonas** [comment]
@carlosabella I think I've fixed the issue but only tested on a virtual machine... 

Can you update and see if it works now?

**Comment by carlosabella** [comment]
Hi there, I am sorry ... I totally forgot to close this issue. It is working perfectly!!

Thanks a lot.
