### ISSUE TITLE
vscode-apex-autocomplete Not working 

### ISSUE THREAD

**Issue by VorenusPullo** [ChuckJonas/vscode-apex-autocomplete#30]
I have got a weird problem.The auto complete is NOT working even for Apex. I am a complete newbie in Salesforce. I installed VS Code and then installed all the Salesforce extensions (https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode) . I then created a sample project(using sfdx command on Git Bash) to start my learning and created a class. But, Somehow, the autocomplete does not work at all. I tried like hell on web but I did not get any solution. Please advise/help. Thanks!!
![installed extensions](https://user-images.githubusercontent.com/21057131/38615480-74456ace-3dae-11e8-99f5-e810837393d0.JPG)
![noautocomplete](https://user-images.githubusercontent.com/21057131/38615481-7478a59c-3dae-11e8-8aea-432380e9ccca.JPG)

**Comment by VorenusPullo** [comment]
Never Mind. I had to set Java Runtime in VSCode-->File-->Setting. Thanks!

**Comment by ChuckJonas** [comment]
hmmm ya I'm not sure how this extension will work side by side with the official salesforce ones..  They kinda provide the same functionality.
