### ISSUE TITLE
Go to definition & peek definition not work well on Windows

### ISSUE THREAD

**Issue by eliver** [ChuckJonas/vscode-apex-autocomplete#5]
VS code pops up **Unable to open '': Invalid file resource (file://c:\users\salesforce\***\src\classes\***.cls).** 
when trying to go to definition.

BTW, the correct path should be "c:\users\salesforce\***\src\classes\***.cls" on windows.

**Comment by ChuckJonas** [comment]
:faceplam: I feel dumb...

Thank for the feedback, I'll get a fix up today!

**Comment by ChuckJonas** [comment]
@eliver I just released a _potential_ fix... Could you update to `0.2.2` and see if it resolves the issue?  I tried to test on a virtual windows machine, but I couldn't get dependancies setup properly

**Comment by eliver** [comment]
@ChuckJonas Thanks for quick response.  In the latest version it shows an error below line
![untitled](https://cloud.githubusercontent.com/assets/9433335/22812147/fead0828-ef7d-11e6-9c17-0c704ddffe14.png)

**Comment by ChuckJonas** [comment]
damn... I really gotta get a windows env setup so I can test these fixes... Just published another fix that I think will get it... let me know either way

**Comment by eliver** [comment]
@ChuckJonas This has been fixed in the latest version. Thanks again.
