### ISSUE TITLE
Problems generated when typing in editor

### ISSUE THREAD

**Issue by k-bentsen** [ChuckJonas/vscode-apex-autocomplete#8]
As I start typing in the editor, problems start to appear output panel. First, a "no viable alternative at input..." error appears:
![screen shot 2017-02-13 at 3 12 36 pm](https://cloud.githubusercontent.com/assets/5178208/22940756/e3e9fd3a-f297-11e6-8c21-65b53c18f3df.png)

If I complete the method call with open & close parantheses, a different error message appears:
![screen shot 2017-02-13 at 3 14 22 pm](https://cloud.githubusercontent.com/assets/5178208/22940823/0c2c6b3e-f298-11e6-9bef-e51b8f3f27fa.png)

Interestingly, if I add a semi-colon to complete a syntactically correct line, the message disappears:
![screen shot 2017-02-13 at 4 17 33 pm](https://cloud.githubusercontent.com/assets/5178208/22940908/54ab1f86-f298-11e6-9ce3-bce53dcd0f65.png)

I verified that this only happens with this extension enabled. Is there an editor setting dependency that I may be missing? Here's what I have in my config:

```
{
    "editor.wordWrap": true,
    "editor.renderWhitespace": "boundary",
    "editor.renderIndentGuides": true,
    "editor.renderControlCharacters": true,
    "editor.renderLineHighlight": "line",
    "editor.scrollBeyondLastLine": false,
    "editor.detectIndentation": false,
    
    "mavensMate.startMavensMateApp": true,
    "mavensMate.compileOnSave": true,
    "mavensMateDesktop.Path.osx": "/Users/kbentsen/MavensMate/MavensMate.app",

    "apexAutoComplete.checkSyntax": true
}
```

Let me know if there's any additional information or debugging you'd like me to provide.
Thanks!

**Comment by ChuckJonas** [comment]
It's because you have `"apexAutoComplete.checkSyntax": true` enabled.  Basically this will tell you anytime the syntax in your code is invalid (and hopefully save you the wait from having to compile it on salesforce).  Unfortunately, the error messages are not the best.

If you don't like this feature, just set `"apexAutoComplete.checkSyntax": false`
