### ISSUE TITLE
Incredibly slow autocompletion time and CPU drain

### ISSUE THREAD

**Issue by Luca-Terrazzan** [ChuckJonas/vscode-apex-autocomplete#9]
Invoking an autocompletion (even normal VS code ones like variable suggestions) takes up to **15 seconds** when this plugin is active. Most funcionalities work though (sneak peek, go to, etc...). Not only this makes the plugin unusable, but also breaks the standard VS Code autocompletion.

Also, while the suggestion process is ongoing, the Java process used to get the autocompletion uses an outrageous amount of CPU (always gets to 100%).

Disabling the extensions solves everything but...I don't get the sweet features you provide :) (great extension btw)

I can provide a list of other extensions I normally use if necessary (none of them provides autocompletion features though).

UPDATE: this issue seems to be strictly related to project dimension. There are much less problems on projects with less than 20-30 classes.

**System info**:
Lenovo Thinkpad X1 Yoga
OS: Windows 8.1
CPU: i5 6300U
RAM: 8GB

**Comment by ChuckJonas** [comment]
You might try turning off `"apexAutoComplete.checkSyntax": false` (although I doubt that will make much of a difference)...  Can you confirm that only one instance of java is running (i guess it could be possible its kicking over multiple java servers)?

This extension is pretty much a proxy for [tooling-force](https://github.com/neowit/tooling-force.com), so I'm not really sure what else couple be going on.

Just as a comparison to how it runs on my machine (`2015 MBP, 2.8 GHz i7, 16gb ram`): 

In a project with 443 classes, the first call run takes about 10-15 second to complete. CPU usage spikes to 100+% during this time.  After that `auto-compete` and `go-to def` respond almost immediately.  CPU usages never goes much higher than 10%.   Memory usages sits around 1.7 GB.

I'm thinking about adding an output console for debugging issues like this.  Maybe when I do it will turn up some issue when how I'm calling tooling-force.

**Comment by Luca-Terrazzan** [comment]
Actually, disabling the check syntax feature helped quite a lot! In fact, I'd say that the extension is now working properly. It's not an ideal fix but the autocompletion was what I was after :)

**Comment by ChuckJonas** [comment]
Interesting... It must just be the shear throughput of requests that are made that was slowing it down (currently does one everytime the file changes).  I'll see if I can add a different mode that does send off so many requests.  Could easily make it fire on save but that doesn't really help since you've probably also just send a compilation request.

**Comment by ChuckJonas** [comment]
@Luca-Terrazzan I went ahead and added a delay (configurable) to the `checkSyntax` functionality so that it doesn't run until X ms (defaulted to 400) after you stop typing.  

I think this should allow you to enable this feature.  If its still slowing things down, you could try increasing the `checkSyntaxDelay` setting.

**Comment by Luca-Terrazzan** [comment]
Supercool, I'll try this feature and get back with some feedback

**Comment by Luca-Terrazzan** [comment]
Tried it a bit (tweaked the delay to 1sec) and seems to be pretty functioning. I guess it's ok for now yay! (the only issue now is that the ongoing java process is sitting permanently at 820MB RAM usage)

**Comment by ChuckJonas** [comment]
Ya, unfortunately I think that's just the price to cache all the structures and relationships. It does seem high, but I don't see that grow very much as you run it longer  (indicating it's probably not a memory leek issue). I'll check with the developer to see if he's maybe storing more structure than needed.
